### ISSUE TITLE
Typechecking ProcessTree fails with "Overlapping implementation"

### ISSUE THREAD

**Issue by shingarov** [sergei-romanenko/spsc-idris#1]
I am trying to have a first look at SPSC-Idris.  In a clean clone, I start by doing `idris --testpkg spsc_idris.ipkg` using current Agda1 (which is 1.3.4 today).  I get:

```
$ idris --testpkg spsc_idris.ipkg
Type checking ./ProcessTree.idr
ProcessTree.idr:46:16-24:
   |
46 | implementation Show Tree where
   |                ~~~~~~~~~
Overlapping implementation: Show (SortedMap k v) already defined
$
```

**Comment by sergei-romanenko** [comment]
The last commit was on May 24, 2018. Since that the Idris implementation has changed (to Idris 2.0). So you may try to use an old Idris version from 2018.

An example of a project using Idris 2.0 is https://github.com/sergei-romanenko/staged-mrsc-idris2 .

**Comment by shingarov** [comment]
Not sure I correctly understand what you mean by "_the Idris implementation has changed (to Idris 2.0)_".  There is Idris1 and there is Idris2; I see `spsc-idris` hasn't been active since the days of Idris1, so this is what I tried with (1.3.4).  I thought it might be an easy fix to update `spsc-idris` to run on today's Idris1 so people (like myself) can study it; this is why I created this Issue.  Are you saying, "don't waste time on studying `spsc-idris` and look at SMRSC instead"?

**Comment by sergei-romanenko** [comment]
You wrote "using current Agda1 (which is 1.3.4 today)", so I just didn't understand that the problem was with Idris 1.3.4.

I've resolved the problem with "overlapping implementation" by giving a name to the implementation of `Show Tree`.

**Comment by shingarov** [comment]
Thank you so much!!!
